--- # Installing HAProxy on Ubuntu mechines.

- name: Add haproxy PPA repository
  apt_repository: repo="ppa:vbernat/haproxy-{{haproxy_version}}" state=present
  tags: packages

- name: Downloading haproxy & keepalived
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
   - haproxy
   - keepalived
  tags: packages

- name: Ensure keepalived is started
  service: name=keepalived state=started enabled=yes

- name: Ensure keepalived conf is set
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf
  notify: Reload keepalived
  tags: configuration 

- name: Copy sysctl params
  copy: src=files/10-haproxy.conf dest=/etc/sysctl.d/
  notify: Reload sysctl

- meta: flush_handlers

- name: Copy SSL Certificates if required
  copy: src=files/certs/ dest=/etc/haproxy/certs.d/
  notify: Reload haproxy

- name: Copy haproxy-status
  copy: src=files/haproxy-status dest=/usr/bin/haproxy-status mode=0755

- name: Enable init script
  replace: dest='/etc/default/haproxy'
    regexp='ENABLED=0'
    replace='ENABLED=1'

- name: Create /etc/haproxy/conf.d
  file: path=/etc/haproxy/conf.d state=directory mode=755

- name: Configuring haproxy.cfg file
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
  notify: Reload haproxy
  tags: configuration

- name: Start haproxy
  service: name=haproxy state=started enabled=yes
