---

- name: Add Kibana Repo Key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  tags:
    - preinstall

- name: Add Kibana Repository
  yum_repository:
    name: kibana
    description: Elasticsearch repository for 7.x packages
    file: kibana
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgcheck: yes
    enabled: yes
  tags:
    - preinstall

- name: Ensure Firewall is stopped
  service: name=firewalld state=stopped enabled=no
  when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '7'
  tags:
    - preinstall

- name: Ensure Firewall is stopped
  service: name=iptables state=stopped enabled=no
  when: ansible_distribution == 'CentOS' and ansible_distribution_version < '7'
  tags:
    - preinstall
