    - name: Test for eth0 interface
      ignore_errors: yes
      shell: ifconfig eth0 | grep -w inet
      register: test_eth0
      tags:
        - hostentries

    - name: hostname entrywith FQDN in /etc/hosts file
      lineinfile: dest=/etc/hosts line="{{ ansible_default_ipv4.address }} {{ ansible_hostname }}.{{ domain_name }} {{ ansible_hostname }}" insertafter="^127.0.0.1" state=present
      tags:
        - hostentries

    - name: hostname entrywith FQDN in /etc/hosts file
      lineinfile: dest=/etc/hosts line="{{ ansible_eth0.ipv4.address }} {{ ansible_hostname }}.{{ domain_name }} {{ ansible_hostname }}" insertafter="^127.0.0.1" state=present
      when: test_eth0.stdout != ""
      tags:
        - hostentries

    - name: Checking the FQDN
      shell: hostname -f
      register: host_fqdn

    - debug: var=host_fqdn.stdout_lines
