---
remote_directory_path:
target_directory:
remote_agent_directory:
agent_directory:
registration_type:
remote_agent_name:
site:
server_gropup:
gateway_IP:
hostname:
gw_port:
manual_settings_resolved:
monitor_network_channels:
password:
agent_installation_manager_executable_path:
agent_installation_manager_directory:
