---
# handlers file for nimsoft
# Restart the service for Nimsoft as changes are executed in robot.cfg
- name: start nimsoft service
  service:
    name: "{{ nimsoft_service }}"
    state: restarted
  tags: restart_handler


# check whether the port 48000 is listen8ing or not
- name: check_port_48000_status
  wait_for:
    host: "{{ hub_ip }}"
    timeout: "{{ hub_timeout }}"
    port: "{{ netstat_port }}"
  tags: netstat_handler
