---
- name: check firewalld installation on redhat or suse
  command: rpm -q firewalld
  args:
    warn: no
  register: firewalld_pkg_query
  ignore_errors: true
  check_mode: no
  changed_when: false
  tags: firewall

- when: (firewalld_pkg_query.get('rc', 1) == 0
      or is_atomic | bool)
  block:
  - name: stop firewalld
    service:
      name: firewalld
      state: stopped
      enabled: no

- meta: flush_handlers
