---
- name: restart iptables
  become: true
  service:
    name: iptables
    state: restarted

- name: ReStart NRPE service Ubuntu16+
  become: true
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: ansible_distribution_major_version|int >= 16 and ansible_system == "Linux" and ansible_os_family == "Debian"
  with_items:
    - nagios-nrpe-server

- name: ReStart NRPE service RedHat7+
  become: true
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
    enabled: yes
  when: ansible_distribution_major_version|int >= 7 and ansible_system == "Linux" and ansible_os_family == "RedHat"
  with_items:
    - nrpe

- name: ReStart NRPE service FreeBSD
  service:
    name: nrpe3
    enabled: yes
    state: restarted
  when: ansible_system == "FreeBSD"

- name: ReStart NRPE service RedHat6
  become: true
  service: name={{ item }} state=restarted enabled=yes
  when: ansible_distribution_major_version|int <= 6 and ansible_os_family == "RedHat"
  with_items:
    - nrpe

- name: ReStart NRPE service Ubuntu14
  become: true
  service: name={{ item }} state=restarted enabled=yes
  when: ansible_distribution_major_version|int <= 14 and ansible_os_family == "Debian"
  with_items:
    - nagios-nrpe-server
