---
- name: ship systemd service
  template:
    src: node_exporter.service.j2
    dest: "/etc/systemd/system/node_exporter.service"
    owner: root
    group: root
    mode: 0644

- name: Setup Docker Storage Driver
  template:
    src: daemon.json.j2
    dest: "/etc/docker/daemon.json"
    owner: root
    group: root
    mode: 0644
  notify: 
    - Restart Docker Service
    - Daemon Restart Docker Service

- name: start the node_exporter service
  systemd:
    name: node_exporter
    state: started
    enabled: yes
    daemon_reload: yes
  failed_when: false
