--- # Trigers from Notify section from task.

- name: Reload Kibana
  service: name=kibana state=restarted enabled=yes

- name: Daemon Reload Kibana
  systemd:
    state: restarted
    daemon_reload: yes
    name: kibana
  when:
    ansible_distribution in ['RedHat', 'CentOS'] and
    ansible_distribution_version|version_compare('7', '>=')
