--- # prereq for the appdynamics
# Check if this port is open on target endpoint
- name: Check if the remote port is open on target host
  wait_for:
    host: "{{ controller_host }}"
    port: "{{ controller_port }}"
    timeout: "{{ controller_timeout }}"
  register: port_open
  tags: port_check                   
#  Check specific space is provided to filesystem
- name: check if there is enough space in /opt/Appdynamics directory
  fail:
    msg: "{{ appdynamics_directory }} Size not Available"
  when: item.mount == "{{ Appdynamics_folder }}"  and item.size_available < "{{ minimum_space }}"
  with_items: "{{ ansible_mounts }}"
  ignore_errors: yes
  register: disk_space
#                
