--- # Trigers from Notify section from task.

- name: Reload haproxy
  service: name=haproxy state=restarted

- name: Reload keepalived
  service: name=keepalived state=restarted

- name: Reload sysctl
  shell: sysctl --system
