--- # EC2 - Start/Stop/Terminate Module Use Example
- hosts: localhost
  connection: local
  remote_user: ansible
  become: yes
  gather_facts: no
  vars_files:
  - files/awscreds.yml
  tasks:
  - name: Manage the state of an instance
    ec2:
     aws_access_key: "{{ aws_id }}"
     aws_secret_key: "{{ aws_key }}"
     region: "{{ aws_region }}"
     instance_ids: i-0f7ec8dc706295dfe
     state: running
