---
- name: configure EC2
  hosts: localhost
  connection: local
  remote_user: ansible
  vars_files:
    - ../group_vars/userdata_init_script
  tasks:

     - name: Prepare UserData Script - files/userdata_init_script.sh
       local_action: template src=../templates/userdata_init_script.j2 dest=../files/userdata_init_script.sh
       tags: 
         - userdata_init_script

     - name: Installing EC2
       local_action:
         module: ec2
         instance_type: t2.micro
         image: ami-ff48629a
         wait: true
         wait_timeout: 300
         region: us-east-2
         vpc_subnet_id: subnet-0d50ec39e0da6c289
         group_id: sg-0a997e7f3037f04c2
         key_name: elan-key
         assign_public_ip: yes
         state: present
         instance_tags:
            Name: "elan-test"
         user_data: "{{ lookup('file', '../files/userdata_init_script.sh') }}"
       register: create_host

     - name: Wait for SSH Service
       wait_for:
         host: "{{ item.public_dns_name }}"
         port: 22
         delay: 60
         timeout: 320
         state: started
       with_items: "{{ create_host.instances }}"
