--- # Install and start HTTPD
- hosts: elanlab
  become: true
  gather_facts: yes
  vars_files: 
    - conf/webdefaults.yml
  tasks:

   - name: Install HTTPD
     yum: name=httpd state=latest

   - name: Start Service
     service: name=httpd state=started

   - name: Prepare index.html
     template: src=../templates/index.html.j2 dest=/var/www/html/index.html
     notify: Restart HTTPD

   - name: verify service is running
     command: service httpd status
     register: result

   - name: Install {{ pkg_lynx}} Web browser
     yum: name={{ pkg_lynx }} state=installed

   - debug: var=result

  handlers:
    - name: Restart HTTPD
      action: service name=httpd state=restarted
