--- 
# Install and start HTTPD
- hosts: elan_httpd:testdemo
  become: true
  gather_facts: yes
  vars_files: 
    - conf/webdefaults.yml
  tasks:

   - name: Disable Firewall
     service: name=firewalld state=stopped enabled=false
     when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '7'
     tags: firewall

   - name: Disable Iptables
     service: name=iptables state=stopped enabled=false
     when: ansible_distribution == 'CentOS' and ansible_distribution_version <= '6.10'
     tags: firewall
    
   - name: Enable Base Repository
     shell: yum-config-manager --enable base
     when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '5'
     tags: install

   - name: Install httpd
     yum: name=httpd state=latest
     tags: install

   - name: Prepare index.html
     template: src=../templates/index.html.j2 dest=/var/www/html/index.html
     notify: Restart HTTPD
     tags: config

   - name: Validating Configuration
     shell: httpd -t 
     tags: config

   - name: Start Service
     service: name=httpd state=started
     tags: install

   - name: verify Port is Listening
     wait_for: port=80 delay=5 timeout=300
     tags: install

   - name: Ensure the default Apache port is 8080
     lineinfile:
       path: /etc/httpd/conf/httpd.conf
       regexp: '^Listen '
       insertafter: '^#Listen '
       line: Listen 80

   - name: Install pkg_lynx Web browser
     yum: name={{ pkg_lynx }} state=installed
     tags: install

  handlers:
    - name: Restart HTTPD
      action: service name=httpd state=restarted
