---

- name: Install HTTPD using Roles
  hosts: elan_app1_httpd
  become: true
  roles:
    - ../roles/httpd

- name: Install HTTPD using Roles
  hosts: elan_app2_httpd
  become: true
  vars_files:
    - ../group_vars/httpd.yaml
  roles:
    - ../roles/httpd
