---
- hosts: localhost
  become: yes
  become_user: "{{ run_user | default('awx') }}"

  tasks:
    - debug:
        msg: Running as {{ run_user }}
      when: run_user is defined

    - name: Check the Current Path
      shell: pwd
      register: path_out

    - name: Check the Server
      shell: hostname -f
      register: server_out

    - debug:
        msg: Running from {{ path_out.stdout }} on {{ server_out.stdout }} using {{ ansible_playbook_python }}

    - name: Inventory Create in Foreman
      shell: tower-cli inventory create --name elan_local_inventory_hosts --organization {{ awx_org }}

    - name: Import Inventory from localhost
      shell: awx-manage inventory_import --inventory-name elan_local_inventory_hosts --source "{{ local_path }}"
      register: import_out
      when: local_path is defined

    - debug: msg="Please define local_path in the ExtraVariables of this Job Template"

    - debug: var=import_out.stderr
