---
- hosts: localhost
  become: yes
  become_user: awx

  tasks:
    - name: Import Inventory from Foreman
      shell: tower-manage inventory_import --inventory-name all_hosts --source ../foreman.py
      register: import_out

    - debug: var=import_out.stdout
