---
- hosts: elan_tower
  become: yes
  become_user: awx

  tasks:
    - name: Check the path and files
      shell: pwd && ls -al
      register: path_out

    - debug: var=path_out.stdout

    - name: Import Inventory from localhost
      shell: awx-manage inventory_import --inventory-name elan_local_inventory_files --source {{ local_path }}/inventory
      register: import_out
      when: local_path is defined

    - debug: msg="Please define local_path in the ExtraVariables of this Job Template"
      when: local_path is not defined

    - debug: var=import_out.stderr
