---
- hosts: localhost
  become: yes
  become_user: "{{ run_user | default('ansible') }}"
  gather_facts: false

  tasks:
    - debug:
        msg: Running as {{ run_user }}
      when: run_user is defined

    - name: Check the path
      shell: pwd
      register: path_out

    - name: Check the Server
      shell: hostname -f
      register: server_out

    - debug:
        msg: Running from {{ path_out.stdout }} on {{ server_out.stdout }}

    - name: Cleanup the hosts_dynamic
      shell: cat /dev/null > hosts_dynamic
      args:
        chdir: ../inventory

    - name: check /var/lib/awx/projects exists
      stat:
        path: /var/lib/awx/projects 
      register: path_stat

    - name: Setfacl for Ansible
      shell: setfacl -m u:ansible:rwx /var/lib/awx/projects
      when: path_stat.stat.exists

    - name: Import AWS Dynamic Inventory to hosts_dynamic
      shell: python ec2.py --list | python ansible-dynamic-inventory-converter.py
      args:
        chdir: ../scripts/dynamic
      ignore_errors: true

    - name: Import Foreman Dynamic Inventory to hosts_dynamic
      shell: python foreman.py --list | python ansible-dynamic-inventory-converter.py
      args:
        chdir: ../scripts/dynamic
