---
- hosts: localhost
  become: yes
  become_user: "{{ run_user | default('awx') }}"

  tasks:
    - debug:
        msg: Running as {{ run_user }}
      when: run_user is defined

    - name: Check the path
      shell: pwd
      register: path_out

    - name: Check the Server
      shell: hostname -f
      register: server_out

    - debug:
        msg: Running from {{ path_out.stdout }} on {{ server_out.stdout }} with {{ lookup('env','PATH') }} using {{ ansible_playbook_python }}

    - name: Cleanup the hosts_dynamic
      shell: cat /dev/null > hosts_dynamic
      args:
        chdir: ../inventory

    - name: Setfacl for Ansible
      shell: setfacl -m u:ansible:rwx /var/lib/awx/projects
      ignore_errors: true

#    - name: Import AWS Dynamic Inventory to hosts_dynamic
#      shell: python ec2.py --list | python ansible-dynamic-inventory-converter.py
#      args:
#        chdir: ../scripts/dynamic

    - name: Import Foreman Dynamic Inventory to hosts_dynamic
      shell: python foreman.py --list | python ansible-dynamic-inventory-converter.py
      args:
        chdir: ../scripts/dynamic

    - name: Auto Push the Changes
      shell: git add -A . && git commit -a -m "Auto Push from AWX" && git push origin master

    - name: Inventory Create in Foreman
      shell: tower-cli inventory create --name elan_foreman_hosts --organization {{ awx_org }}

    - name: Import Inventory from Foreman
      shell: awx-manage inventory_import --inventory-name elan_foreman_hosts --source {{ clone_path }}/foreman.py
      register: import_out
      when: clone_path is defined

    - debug: var=import_out.stdout

    - debug: msg="Please define clone_path in the ExtraVariables of this Job Template"
      when: clone_path is not defined

    - debug: var=import_out.stderr
