---
- hosts: localhost
  become: yes
  become_user: awx

  tasks:
    - name: Check the path and files
      shell: pwd && ls -al
      register: path_out

    - debug: var=path_out.stdout

    - name: Import Inventory from Foreman
      shell: tower-manage inventory_import --inventory-name all_hosts --source {{ clone_path }}/foreman.py
      register: import_out
      when: clone_path is defined

    - debug: var=import_out.stdout

    - debug: msg="Please define clone_path in the ExtraVariables of this Job Template"
      when: clone_path is not defined

    - debug: var=import_out.stderr
