---
#install nginx
- hosts: elan_nginx
  become: true
  gather_facts: yes
  vars_files:
    - ../group_vars/nginx

  tasks:

    - name: Disable Firewall
      service: name=firewalld state=stopped enabled=false
      when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '7'
      tags: firewall

    - name: Enable Base Repository
      shell: yum-config-manager --enable base
      when: ansible_distribution == 'CentOS' and ansible_distribution_version >= '5'
      tags: install

    - name: Disable Iptables
      service: name=iptables state=stopped enabled=false
      when: ansible_distribution == 'CentOS' and ansible_distribution_version <= '6.10'
      tags: firewall

    - name: Install nginx
      yum: name=nginx state=latest

    - name: Ensure the default port is custom
      template: src=../templates/nginx/default.conf.j2 dest=/etc/nginx/conf.d/default.conf
      notify: Restart nginx

    - name: Prepare index.html
      template: src=../templates/index.html.j2 dest=/usr/share/nginx/html/index.html
      notify: Restart nginx

    - name: Validating Configuration
      shell: nginx -t
      tags: config

    - name: Start service
      service: name=nginx state=started
      tags: install

    - name: Verify Port is Listening
      wait_for: port={{ nginx_port }} delay=5 timeout=300
      tags: install

    - name: Install pkg_lynx Web browser
      yum: name={{ pkg_lynx }} state=installed
      tags: install


  handlers:
    - name: Restart nginx
      action: service name=nginx state=restarted
