---
- hosts: localhost
  user: ansible
  become: true
  gather_facts: no
  vars_files:
    - ../group_vars/aws

  tasks:

   - set_fact: az=us_east_1a

   - name: Print Values
     debug: msg="NFS Server for {{ az }} is '{{ facts["az"].nfs_server }}'"
