- hosts: test
  become: yes

  tasks:
    - name: Set authorized key taken from file
      authorized_key:
        user: elanadmin
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
